# Generated by Django 4.1.3 on 2022-11-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List_tasks',
            new_name='ListTasks',
        ),
    ]
