# Generated by Django 4.1.3 on 2022-11-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_remove_task_owner_listtasks_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listtasks',
            name='color',
        ),
        migrations.AlterField(
            model_name='listtasks',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
