# Generated by Django 4.1.3 on 2022-12-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_remove_listtasks_color_alter_listtasks_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
