# Generated by Django 4.1.3 on 2022-12-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0005_task_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='order',
            new_name='order_home',
        ),
        migrations.AddField(
            model_name='task',
            name='order_list',
            field=models.IntegerField(null=True),
        ),
    ]
