# Generated by Django 4.1.3 on 2022-12-05 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('to_do_list', '0006_rename_order_task_order_home_task_order_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtasks',
            name='members',
            field=models.ManyToManyField(related_name='list_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
